CRITICAL - 2022-12-11 12:02:21 --> Class "Config\Database" not found
in SYSTEMPATH\Model.php on line 137.
 1 APPPATH\Controllers\UserCrud.php(9): CodeIgniter\Model->__construct()
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\UserCrud->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-11 12:06:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'test'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'root', 'demo', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-11 12:06:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-11 12:13:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'test'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'root', 'demo', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-11 12:13:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-11 12:18:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'test'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'root', 'demo', 3306, '', 0)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#9 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CodeIgn\CI\CI\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CodeIgn\CI\CI\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CodeIgn\CI\CI\system\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CodeIgn\CI\CI\app\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(927): App\Controllers\UserCrud->index()
#7 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
#8 C:\xampp\htdocs\CodeIgn\CI\CI\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CodeIgn\CI\CI\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CodeIgn\CI\CI\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-11 12:18:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(585): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\UserCrud.php(10): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\UserCrud->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-11 12:36:01 --> Invalid file: edit_user.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('edit_user.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('edit_user', [], true)
 3 APPPATH\Controllers\UserCrud.php(32): view('edit_user', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\UserCrud->singleUser('16')
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserCrud))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
